"""
output_formats.py — Deterministic Display Response and Executive Summary
=============================================================================
Gap-closure Phase 4. Implements Format 1 (§2) and Format 2 (§3) of
LLM_Output_Specification_CAG_Statutory_Auditor_Report_Review.md — the
short, exception-driven, action-oriented outputs, generated by plain
Python string templating over the already-built Observation list.

WHY NO LLM CALL FOR THESE TWO FORMATS
------------------------------------------
The spec's §17 "Single Source of Truth" requirement is explicit: the
Display Response, Executive Summary and Detailed Report "should be
generated from the same structured data" so they "do not contain
different conclusions, different risk ratings or different
prioritisation." The only way to *guarantee* that — not just hope for it
— is for at least the two shorter, fully-structural formats to be built by
straight formatting of the Observation list, not by asking an LLM to
summarise it in its own words a second time (which reintroduces exactly
the risk of drift the spec is warning against). Every sentence these two
functions produce is templated from a field already on `Observation` or
`PackageContext` — nothing here is generated text.

GAP-CLOSURE PHASE 5 UPDATE — Format 3 (Detailed Review Report) now built
----------------------------------------------------------------------------
`render_detailed_report()` below builds the spec's full 16-section TOC.
13 of the 16 sections (1, 3, 4, 7-16) are deterministic templating over the
same Observation list and package data as Formats 1/2 — same "cannot
disagree" guarantee. Sections 5 and 6 (Opinion Analysis narrative, Detailed
Component Review) are NOT rebuilt as templates: they call for actual prose
synthesis (assessing whether wording is "hedged", judging whether a KAM
reads as boilerplate, etc.) that a template cannot responsibly produce, so
those two sections embed the existing LLM writer's own PART 2 output
verbatim, clearly labelled as LLM-generated narrative — a deliberate hybrid,
not a gap papered over. See GAP_CLOSURE_LOG.md, Phase 5, for the honest
limitations on this (mainly: the embedded narrative was NOT re-derived from
`observations` and so is the one place in this document where a drift
between the deterministic sections and the narrative is possible in
principle, though not observed in this phase's real-data test run).
"""

from __future__ import annotations

from dataclasses import dataclass

from sar_prod_v3.observation import Observation

_TAG_ORDER = {"FINDING": 0, "RISK_FLAG": 1, "AUDIT_POINTER": 2}
_RISK_ORDER = {"High": 0, "Medium": 1, "Low": 2, "Information request only": 3}
_TAG_DISPLAY = {"FINDING": "FINDING", "RISK_FLAG": "RISK FLAG", "AUDIT_POINTER": "AUDIT POINTER"}

_CONSISTENCY_LABELS = [
    ("FS_AR", "FS ↔ Audit Report"),
    ("FS_CARO", "FS ↔ CARO"),
    ("AR_CARO", "Audit Report ↔ CARO"),
    ("FS_AR_CARO", "FS ↔ Audit Report ↔ CARO"),
]

_CAVEAT_LINE = "AI-assisted review; subject to human audit judgement."


@dataclass
class PackageContext:
    """The package-level facts both render functions need, alongside the
    Observation list. Deliberately a small, explicit set — everything else
    a format needs should already live on an Observation."""
    entity: str
    financial_year: str
    scope: str
    opinion_type: str
    review_status: str
    review_status_reasons: list[str]


def _sort_key(obs: Observation) -> tuple:
    return (_TAG_ORDER.get(obs.tag, 9), _RISK_ORDER.get(obs.risk_rating, 9))


def _material_observations(observations: list[Observation]) -> list[Observation]:
    """Sorted most-material-first: FINDING before RISK_FLAG before
    AUDIT_POINTER, High before Medium before Low before Information-
    request-only within each tag."""
    return sorted(observations, key=_sort_key)


def _why_it_matters(obs: Observation) -> str:
    """The audit-risk / gap explanation, falling back to the observation
    text itself when neither is set. That fallback is load-bearing in
    render_display_response (§2), the one format where this is the only
    place the observation's actual content appears at all. In
    render_detailed_report (§4), `obs.observation` is already printed
    immediately beside every call site below — see `_why_it_matters_detail`
    there for the version that avoids repeating it a second time."""
    return obs.audit_risk or obs.gap or obs.observation


def _why_it_matters_detail(obs: Observation) -> str:
    """Same as `_why_it_matters`, but for contexts where `obs.observation`
    is already shown right next to this — returns "" instead of repeating
    it verbatim. Used only in render_detailed_report's §12 table/narrative,
    which used to print the identical sentence twice per observation (once
    as "Observation"/"Issue", once again as "Why It Matters") whenever
    `audit_risk`/`gap` were unset, which is the common case for
    AUDIT_POINTER/RISK_FLAG checks."""
    why = _why_it_matters(obs)
    return why if why != obs.observation else ""


def _source_label(obs: Observation) -> str:
    parts = [k.replace("_", " ").title() for k, v in obs.source.items() if v]
    if parts:
        return " / ".join(parts)
    # OTHER-classified checks (formal/applicability/pre-flight) have no
    # document-comparison bucket — fall back to the component name.
    return obs.component


def _recommended_action(obs: Observation) -> str:
    if obs.recommended_audit_action:
        return obs.recommended_audit_action[0]
    return "Raise audit query and obtain the statutory auditor's explanation."


def _overall_coherence(observations: list[Observation]) -> str:
    coherence_issues = [
        o for o in observations
        if o.sa_framework and o.sa_framework.get("opinion_coherence_issue") in ("Yes", "Requires Evidence")
    ]
    if not coherence_issues:
        return "No material opinion-coherence issues identified from the supplied package."
    high = sum(1 for o in coherence_issues if o.risk_rating == "High")
    return (
        f"{len(coherence_issues)} opinion-coherence matter(s) identified"
        f"{f' ({high} High risk)' if high else ''} — see Key Observations."
    )


def _information_limitations(ctx: PackageContext) -> str:
    if ctx.review_status == "complete":
        return "None material."
    return " ".join(ctx.review_status_reasons) or f"Review status: {ctx.review_status}."


# ---------------------------------------------------------------------------
# Format 1 — LLM Display Response (§2)
# ---------------------------------------------------------------------------

def render_display_response(ctx: PackageContext, observations: list[Observation], *, max_observations: int = 10) -> str:
    ordered = _material_observations(observations)
    high_risk_count = sum(1 for o in ordered if o.risk_rating == "High")
    key_obs = ordered[:max_observations]

    lines: list[str] = []
    lines.append(f"{ctx.entity} / {ctx.financial_year} / {ctx.scope.upper()}")
    lines.append("")
    lines.append("OVERALL REVIEW STATUS")
    lines.append(f"Opinion: {ctx.opinion_type or 'Unclear'}")
    lines.append(f"Overall coherence: {_overall_coherence(observations)}")
    lines.append(f"High-risk matters: {high_risk_count}")
    lines.append(f"Information limitations: {_information_limitations(ctx)}")
    lines.append("")

    lines.append("KEY OBSERVATIONS")
    if not key_obs:
        lines.append("No findings. No risk flags. No audit pointers.")
    for i, obs in enumerate(key_obs, 1):
        lines.append(f"{i}. [{obs.component}] — {_TAG_DISPLAY.get(obs.tag, obs.tag)}")
        lines.append(f"   Why it matters: {_why_it_matters(obs)}")
        lines.append(f"   Source: {_source_label(obs)}")
        lines.append(f"   Recommended action: {_recommended_action(obs)}")
    lines.append("")

    lines.append("CONSISTENCY ALERTS")
    for consistency_type, label in _CONSISTENCY_LABELS:
        matches = [o for o in ordered if o.consistency_type == consistency_type]
        if matches:
            summary = "; ".join(f"{o.component} ({o.risk_rating})" for o in matches[:3])
            lines.append(f"{label}: {summary}")
        else:
            lines.append(f"{label}: No material inconsistency identified.")
    lines.append("")

    lines.append("IMMEDIATE AUDIT ACTIONS")
    actions: list[str] = []
    for obs in key_obs:
        action = _recommended_action(obs)
        if action not in actions:
            actions.append(action)
        if len(actions) >= 3:
            break
    if not actions:
        lines.append("None — no material observation requires immediate follow-up.")
    else:
        for i, action in enumerate(actions, 1):
            lines.append(f"{i}. {action}")
    lines.append("")

    lines.append("CAVEAT")
    lines.append(_CAVEAT_LINE)

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Format 2 — Executive Summary Report (§3)
# ---------------------------------------------------------------------------

def render_executive_summary(ctx: PackageContext, observations: list[Observation]) -> str:
    ordered = _material_observations(observations)
    findings_and_flags = [o for o in ordered if o.tag in ("FINDING", "RISK_FLAG")]
    silence_matters = [
        o for o in ordered
        if o.tag == "RISK_FLAG" and "silence" in (o.observation or "").lower()
    ]
    candidates_143_6 = [o for o in ordered if o.candidate_143_6]

    lines: list[str] = []
    lines.append(f"# Executive Summary — {ctx.entity} {ctx.financial_year} ({ctx.scope})")
    lines.append("")

    lines.append("## 1. Report Identification and Scope")
    lines.append(f"Entity: {ctx.entity}  |  Financial Year: {ctx.financial_year}  |  Scope: {ctx.scope}")
    lines.append("")

    lines.append("## 2. Overall Review Conclusion")
    lines.append(_overall_coherence(observations))
    lines.append(f"Review status: {ctx.review_status}.")
    if ctx.review_status != "complete":
        lines.append(" ".join(ctx.review_status_reasons))
    lines.append("")

    lines.append("## 3. Statutory Auditor Opinion Summary")
    lines.append(f"Opinion: {ctx.opinion_type or 'Unclear'}")
    lines.append("")

    lines.append("## 4. Top Findings and Risk Flags")
    if not findings_and_flags:
        lines.append("No findings. No risk flags.")
    for obs in findings_and_flags[:10]:
        lines.append(
            f"- **[{obs.observation_id}] {_TAG_DISPLAY.get(obs.tag, obs.tag)} ({obs.risk_rating})** "
            f"{obs.component} — {obs.observation}"
        )
    lines.append("")

    lines.append("## 5. FS – Audit Report – CARO Consistency Summary")
    lines.append("| Combination | Result | Observation IDs |")
    lines.append("|---|---|---|")
    for consistency_type, label in _CONSISTENCY_LABELS:
        matches = [o for o in ordered if o.consistency_type == consistency_type]
        result = "Follow-up required" if matches else "Consistent"
        ids = ", ".join(o.observation_id for o in matches) or "—"
        lines.append(f"| {label} | {result} | {ids} |")
    lines.append("")

    lines.append("## 6. Material Silence / Gap Matters")
    if not silence_matters:
        lines.append("No material silence matters identified from the supplied package.")
    for obs in silence_matters:
        lines.append(f"- [{obs.observation_id}] {obs.observation}")
    lines.append("")

    lines.append("## 7. Priority Audit Actions")
    seen_actions: list[str] = []
    for obs in findings_and_flags:
        for action in (obs.recommended_audit_action or [_recommended_action(obs)]):
            if action not in seen_actions:
                seen_actions.append(action)
    if not seen_actions:
        lines.append("None required.")
    for i, action in enumerate(seen_actions[:10], 1):
        lines.append(f"{i}. {action}")
    lines.append("")

    if candidates_143_6:
        lines.append("## 7a. Candidate Section 143(6) Matters (draft — human review required)")
        for obs in candidates_143_6:
            lines.append(f"- [{obs.observation_id}] {obs.component}: {obs.observation}")
        lines.append("")

    lines.append("## 8. Information Limitations / Caveats")
    lines.append(_information_limitations(ctx))
    lines.append(_CAVEAT_LINE)

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Format 3 — Detailed Review Report (§4-§14, 16-section TOC)
# ---------------------------------------------------------------------------

def _extract_narrative_part2(existing_report_md: str) -> str:
    """Pulls PART 2 out of the existing LLM writer's markdown (see
    PROMPT.md's REPORT_WRITER section) for embedding as sections 5/6's
    narrative. Falls back to the whole document if the marker isn't found
    (older report shape, or a failed generation) rather than returning
    nothing — a mislabelled narrative is still better than a silently
    empty section."""
    marker = "## PART 2"
    idx = (existing_report_md or "").find(marker)
    return existing_report_md[idx:] if idx != -1 else (existing_report_md or "")


def _applicability_row(applicability: dict, area: str, label: str) -> str:
    result = (applicability or {}).get(area) or {}
    status = result.get("status", "uncertain")
    basis = result.get("basis", "")
    return f"| {label} | {status} | {basis} | current assignment year | {'Verified' if status != 'uncertain' else 'Requires Verification'} |"


def render_detailed_report(
    ctx: PackageContext,
    observations: list[Observation],
    *,
    merged_json: dict,
    applicability: dict,
    quality_flags: dict,
    doc_meta: dict,
    existing_report_md: str,
) -> str:
    """Format 3 — the spec's full 16-section TOC (§5). See this module's
    docstring for which sections are deterministic vs. embedded narrative.
    """
    ordered = _material_observations(observations)
    lines: list[str] = []

    # 1. Report Control Sheet
    lines.append("# SAR Detailed Review Report")
    lines.append("")
    lines.append("## 1. Report Control Sheet")
    lines.append(f"- Entity: {ctx.entity}")
    lines.append(f"- Financial Year: {ctx.financial_year}")
    lines.append(f"- Scope: {ctx.scope}")
    lines.append(f"- Source document: {doc_meta.get('doc_name', 'Unknown')} ({doc_meta.get('total_pages', '?')} pages)")
    lines.append(f"- Review status: {ctx.review_status}")
    lines.append("- Output specification: LLM_Output_Specification_CAG_Statutory_Auditor_Report_Review.md")
    lines.append("")

    # 2. Executive Summary — a short synopsis only, not the full Format 2
    # output. This used to embed render_executive_summary()'s complete text
    # verbatim, including its own H1 title and its own nested "1."-"8."
    # numbering — which duplicated Top Findings (§4), the CARO consistency
    # table (§5) and Silence matters (§6) that this Detailed Report already
    # covers in full, later, in its own §7 (CARO consistency), §8
    # (Silence), §9 (Public-Sector) and §12 (the complete observation
    # register, both a table and a per-observation narrative block). That
    # made every C&AG-direction-style observation print 3-4 times over and
    # put a second, competing numbering scheme inside this section. §17's
    # "single source of truth" requirement is about the *data* agreeing
    # across formats, not about literally reprinting one format inside
    # another — Format 2 stays available on its own via the Executive
    # Summary tab for a reviewer who wants only that.
    lines.append("## 2. Executive Summary")
    lines.append(_overall_coherence(observations))
    lines.append(f"Opinion: {ctx.opinion_type or 'Unclear'}  |  Review status: {ctx.review_status}")
    if ctx.review_status != "complete":
        lines.append(" ".join(ctx.review_status_reasons))
    lines.append("")

    # 3. Input Package and Review Status
    lines.append("## 3. Input Package and Review Status")
    for k, v in (quality_flags or {}).items():
        lines.append(f"- {k.replace('_', ' ').title()}: {v}")
    if ctx.review_status != "complete":
        lines.append(f"- Review status reasons: {' '.join(ctx.review_status_reasons)}")
    lines.append("")

    # 4. Scope and Assignment Context
    lines.append("## 4. Scope and Assignment Context")
    lines.append(f"- Entity: {ctx.entity} | Financial Year: {ctx.financial_year} | Scope: {ctx.scope}")
    lines.append(f"- Opinion type: {ctx.opinion_type}")
    lines.append("")

    # 5 & 6 — embedded LLM narrative (see module docstring: not templated)
    lines.append("## 5-6. Statutory Auditor's Opinion Analysis and Detailed Component Review")
    lines.append("_The following is generated by the report-writer LLM from the same structured")
    lines.append("data package as the deterministic sections above and below; it is not itself")
    lines.append("templated from `observations` — see GAP_CLOSURE_LOG.md, Phase 5, for why._")
    lines.append("")
    lines.append(_extract_narrative_part2(existing_report_md))
    lines.append("")

    # 7. FS - Audit Report - CARO Consistency Analysis (§6 of the output spec)
    lines.append("## 7. FS – Audit Report – CARO Consistency Analysis")
    lines.append("| Combination | Result | Material Inconsistency | SA 700/705 Relevance | Observation ID |")
    lines.append("|---|---|---|---|---|")
    combo_matches: dict[str, list[Observation]] = {}
    for consistency_type, label in _CONSISTENCY_LABELS:
        matches = [o for o in ordered if o.consistency_type == consistency_type]
        combo_matches[consistency_type] = matches
        result = "Follow-up" if matches else "Consistent"
        sa_rel = "; ".join(sorted({o.sa_framework["standard"] for o in matches if o.sa_framework})) or "N/A"
        ids = ", ".join(o.observation_id for o in matches) or "—"
        lines.append(f"| {label} | {result} | {'Yes' if matches else 'No'} | {sa_rel} | {ids} |")
    lines.append("")
    lines.append("_Only inconsistent/material combinations are expanded below — per the output_")
    lines.append("_specification's own rule against pages of \"consistent\" results._")
    for consistency_type, label in _CONSISTENCY_LABELS:
        matches = combo_matches[consistency_type]
        if not matches:
            continue
        lines.append(f"\n**{label}:**")
        for obs in matches:
            lines.append(f"- [{obs.observation_id}] {obs.component} — {obs.observation}")
            lines.append(f"  SA 700/705 relevance: {obs.sa_framework['standard'] if obs.sa_framework else 'N/A'} | Risk: {obs.risk_rating}")
    lines.append("")

    # 8. Silence and Material Gap Analysis
    lines.append("## 8. Silence and Material Gap Analysis")
    silence_matters = [o for o in ordered if o.tag == "RISK_FLAG" and "silence" in (o.observation or "").lower() or "echo" in (o.observation or "").lower()]
    if not silence_matters:
        lines.append("No material silence matters identified from the supplied package.")
    else:
        lines.append("| FS Matter | Expected Report Location | Auditor Report Position | Significance | Recommended Action |")
        lines.append("|---|---|---|---|---|")
        for obs in silence_matters:
            action = obs.recommended_audit_action[0] if obs.recommended_audit_action else "Raise audit query."
            lines.append(f"| {obs.component} | {obs.component} | Not identified in supplied package | {obs.risk_rating} | {action} |")
    lines.append("")

    # 9. Public-Sector / High-Sensitivity Matters (conditional)
    lines.append("## 9. Public-Sector / High-Sensitivity Matters")
    ps_matters = [o for o in ordered if o.public_sector_lens]
    if not ps_matters:
        lines.append("No separately reportable public-sector sensitivity was identified from the supplied package.")
    else:
        for obs in ps_matters:
            lines.append(f"- [{obs.observation_id}] {obs.component} — nature: {obs.public_sector_lens.get('nature')}")
    lines.append("")

    # 10. Consolidated / Group Matters. Always rendered — omitting the
    # heading entirely for a standalone-scope report (the common case) used
    # to make the TOC jump straight from "9." to "12.", silently skipping
    # 10 and 11, which is exactly what looked like broken numbering. Every
    # other conditional section in this function (9, 13) keeps its heading
    # and prints a "none identified" fallback instead; this now matches.
    lines.append("## 10. Consolidated / Group Matters")
    if ctx.scope == "consolidated":
        lines.append("Group-audit-specific checks are not yet implemented in this pipeline — see GAP_CLOSURE_LOG.md.")
    else:
        lines.append(f"Not applicable — this review's scope is {ctx.scope}, not consolidated.")
    lines.append("")

    # 11. Prior-Year / Continuing Matters. Always rendered — see §10's note above.
    lines.append("## 11. Prior-Year / Continuing Matters")
    prior_matters = [o for o in ordered if o.check_id == "PRIOR-OPN-01"]
    if not prior_matters:
        lines.append("No prior-year or continuing matters were identified from the supplied package.")
    else:
        for obs in prior_matters:
            lines.append(f"- [{obs.observation_id}] {obs.observation}")
    lines.append("")

    # 12. Observations, Audit Pointers and Evidence Required (merged register)
    lines.append("## 12. Observations, Audit Pointers and Evidence Required")
    lines.append("| ID | Observation | Tag | Risk | Source | Why It Matters | Evidence / Audit Pointer | Reviewer Action |")
    lines.append("|---|---|---|---|---|---|---|---|")
    for obs in ordered:
        evidence = "; ".join(obs.evidence_required) or "—"
        lines.append(
            f"| {obs.observation_id} | {obs.observation} | {_TAG_DISPLAY.get(obs.tag, obs.tag)} | "
            f"{obs.risk_rating} | {_source_label(obs)} | {_why_it_matters_detail(obs) or '—'} | {evidence} | {obs.reviewer_status} |"
        )
    lines.append("")
    for obs in ordered:
        lines.append(f"**Observation {obs.observation_id}** (Check ID: {obs.check_id})")
        lines.append(f"- Issue: {obs.observation}")
        lines.append(f"- Classification: {_TAG_DISPLAY.get(obs.tag, obs.tag)} | Risk: {obs.risk_rating} | Confidence: {obs.confidence}")
        lines.append(f"- Source: {_source_label(obs)}")
        if obs.sa_framework:
            lines.append(f"- SA 700/705 consideration: {obs.sa_framework['standard']} ({obs.sa_framework['nature']})")
        why = _why_it_matters_detail(obs)
        if why:
            lines.append(f"- Why it matters: {why}")
        if obs.evidence_required:
            lines.append(f"- Evidence required: {'; '.join(obs.evidence_required)}")
        if obs.caveats:
            lines.append(f"- Caveats: {' '.join(obs.caveats)}")
        lines.append(f"- Reviewer decision: {obs.reviewer_status}")
        lines.append("")

    # 13. Candidate Section 143(6) Matters
    lines.append("## 13. Candidate Matters for Consideration under Section 143(6)")
    candidates = [o for o in ordered if o.candidate_143_6]
    if not candidates:
        lines.append("No observation in this review meets the threshold for a candidate section 143(6) matter (clear source trace + materiality + tag=FINDING at High risk).")
    for obs in candidates:
        lines.append(f"\n**Candidate Matter {obs.observation_id}**")
        lines.append(f"- Source established: {obs.evidence}")
        lines.append(f"- References: {_source_label(obs)}")
        lines.append(f"- Issue: {obs.observation}")
        lines.append(f"- Financial/Reporting impact: {obs.audit_risk or 'Not established from the supplied package.'}")
        lines.append(f"- Public-sector relevance: {obs.public_sector_lens or 'Not classified as public-sector-sensitive.'}")
        lines.append(f"- Evidence pending: {'; '.join(obs.evidence_required) or 'None identified.'}")
        lines.append(f"- Draft safe wording: {obs.safe_candidate_wording or '(not drafted)'}")
        lines.append("- Status: DRAFT — HUMAN REVIEW REQUIRED")
    lines.append("")

    # 14. Limitations and Caveats
    lines.append("## 14. Limitations and Caveats")
    lines.append("| Limitation | Affected Analysis | Impact | Required Action |")
    lines.append("|---|---|---|---|")
    if ctx.review_status != "complete":
        for reason in ctx.review_status_reasons:
            lines.append(f"| {reason} | Overall review | Review status: {ctx.review_status} | Resolve before relying on High-confidence observations |")
    all_caveats = {c for o in ordered for c in o.caveats}
    for caveat in all_caveats:
        lines.append(f"| {caveat} | Individual observation(s) | Confidence/tag adjusted | Verify against source |")
    lines.append("")

    # 15. Reviewer Action Summary
    lines.append("## 15. Reviewer Action Summary")
    lines.append("| Priority | Observation ID | Action | Responsible Person / Team | Evidence Required | Status |")
    lines.append("|---|---|---|---|---|---|")
    for obs in [o for o in ordered if o.tag in ("FINDING", "RISK_FLAG", "AUDIT_POINTER")]:
        action = obs.recommended_audit_action[0] if obs.recommended_audit_action else "Raise audit query."
        lines.append(
            f"| {obs.risk_rating} | {obs.observation_id} | {action} | Audit team | "
            f"{'; '.join(obs.evidence_required) or '—'} | {obs.reviewer_status} |"
        )
    lines.append("")

    # 16. Annexures
    lines.append("## 16. Annexures")
    lines.append("\n### Annexure A — Documents Reviewed and Source Index")
    lines.append("| Document ID | Document | Pages | Scope | Quality |")
    lines.append("|---|---|---|---|---|")
    lines.append(f"| {doc_meta.get('doc_id', '?')} | {doc_meta.get('doc_name', '?')} | {doc_meta.get('total_pages', '?')} | {ctx.scope} | {quality_flags.get('main_text', 'unknown')} |")

    lines.append("\n### Annexure B — Report Component Mapping")
    lines.append("| Component | Retrieval Quality |")
    lines.append("|---|---|")
    for comp, qkey in [
        ("Main Report", "main_text"), ("CARO", "caro_text"), ("IFC", "ifc_text"),
        ("Directors' Report", "dir_report"), ("Financial Statements", "fs_tables"),
    ]:
        lines.append(f"| {comp} | {quality_flags.get(qkey, 'unknown')} |")

    lines.append("\n### Annexure C — Detailed CARO Clause Status")
    lines.append("| CARO Clause | Status | Adverse / Qualified Matter | Observation ID |")
    lines.append("|---|---|---|---|")
    caro_clauses = (merged_json.get("CARO_2020") or {}).get("clauses") or []
    if not caro_clauses:
        lines.append("| — | Not extracted / not applicable | — | — |")
    for clause in caro_clauses:
        status = clause.get("answer", "unknown")
        matter = "No material inconsistency identified." if status == "clean" else (clause.get("verbatim_quote") or "")
        related = next((o.observation_id for o in ordered if clause.get("clause_no", "") in (o.check_id or "")), "—")
        lines.append(f"| ({clause.get('clause_no', '?')}) | {status} | {matter[:150]} | {related} |")

    directions_obs = [o for o in ordered if o.check_id.startswith("DIR-")]
    if directions_obs:
        lines.append("\n### Annexure D — C&AG Directions Status")
        lines.append("| Direction | Addressed | Observation ID |")
        lines.append("|---|---|---|")
        for obs in directions_obs:
            lines.append(f"| {obs.component} | {'No' if obs.tag != 'AUDIT_POINTER' else 'Partially'} | {obs.observation_id} |")

    lines.append("\n### Annexure E — Framework / Applicability Verification")
    lines.append("| Requirement | Applicability | Basis | Version / Year | Verification Status |")
    lines.append("|---|---|---|---|---|")
    lines.append(_applicability_row(applicability, "caro", "CARO"))
    lines.append(_applicability_row(applicability, "kam", "KAM"))
    lines.append(_applicability_row(applicability, "ifc", "IFC"))

    lines.append("\n### Annexure F — Machine-Readable Observation Data")
    lines.append(
        f"{len(observations)} structured observation(s) available as the `observations` field of this "
        f"pipeline's JSON output — not reproduced inline here per the output specification's own note "
        f"that this annexure need not be printed in the rendered report."
    )

    return "\n".join(lines)
